name: Deploy Frontend
on:
  workflow_run:
    workflows: ["Deploy Backend"]
    types:
      - completed

jobs:

  deploy_frontend:

    name: Deploy Frontend
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
        working-directory: frontend

      - name: Build frontend
        run: |
          CI=false npm run build
        working-directory: frontend

      - name: Deploy frontend to Render
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
